// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dizujgexokqewwbxfakb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpenVqZ2V4b2txZXd3YnhmYWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjc5ODMsImV4cCI6MjA2Njg0Mzk4M30.d_BqajCHMZdDHkjXlXa67fpug5QkPXbapBFgzqkZpuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});