// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nktkwsadkmfcljnnoehq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdGt3c2Fka21mY2xqbm5vZWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTM5NzQsImV4cCI6MjA2Nzc2OTk3NH0.Dd0mnSsTxi-hyIx6a5cwwyCrkOzAzhtAmCtg9LSHCu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});