// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgftxekxmwlwbpukjkne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZnR4ZWt4bXdsd2JwdWtqa25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODAxNTEsImV4cCI6MjA2ODI1NjE1MX0.Q6uKJ7nIcZgE9DtMtstl8-LZGR654yfdpWOJtf_y-KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});